# Generated by Django 4.2.11 on 2024-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='course_topic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='course_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_topic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_type',
            field=models.TextField(null=True),
        ),
    ]
