# Generated by Django 4.2.11 on 2024-07-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0030_courseoverview_course_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='no_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='no_grade',
            field=models.BooleanField(default=False),
        ),
    ]
